pagination
onyxtec/pulse pull request #1
Opened 2021-11-05 11:00 UTC by kaynat1234

2021-11-08 06:28 UTC, onyxtec requested changes

2021-11-08 06:28 UTC, onyxtec commented on app/Http/Controllers/FeedbackController.php
>          $user= $feedback->user_id;
Always name id with id e.g. `$userId`
Having $user containing only id would be very confusing.

Similarly naming a user record in User::find as $userschema is confusing, `find` returns you the object or user object and not just schema so that should be just `$user`

Your variable naming guiding what is what is very critical for good code and others to work with you and not be confused about variable & function names.

When it seems hard to name correctly, drop a comment above the line for ease of code reading.

2021-11-08 06:28 UTC, onyxtec commented on config/fortify.php
> +        //Features::registration(),
I don't even know what this does, standard way of disabling registration is `register => false` in web.php

https://www.itsolutionstuff.com/post/laravel-disable-registration-route-exampleexample.html

2021-11-08 06:28 UTC, onyxtec commented on routes/web.php
> +
Avoid extra spaces. There should never be more than one empty line.

All other code changes look good.

2021-11-08 06:36 UTC, kaynat1234 commented on app/Http/Controllers/FeedbackController.php
>          $user= $feedback->user_id;
okay sure, I will change these variables accordingly.

2021-11-08 06:39 UTC, kaynat1234 commented on config/fortify.php
> +        //Features::registration(),
Actually I have also tried this way but it didn't work. I think so it was due to upgraded version of laravel.

2021-11-09 07:47 UTC, onyxtec approved these changes

2021-11-09 07:47 UTC, merged